config/routes.rb
Rails.application.routes.draw do
  get 'lawnbowls/new'

  get 'scots/new'

  get 'teams/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'team'    => 'scots#team'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'news'    => 'static_pages#news'
  get 'newgames' => 'static_pages#newgames'
  get 'late'     => 'static_pages#late'
  get 'one'     => 'static_pages#one'
  get 'two'     => 'static_pages#two'
  get 'three'     => 'static_pages#three'
  get 'four'     => 'static_pages#four'
  get 'five'     => 'static_pages#five'
  get 'six'     => 'static_pages#six'
  get 'seven'     => 'static_pages#seven'
  get 'eight'     => 'static_pages#eight'
  get 'nine'     => 'static_pages#nine'
  get 'ten'     => 'static_pages#ten'
  get 'eleven'     => 'static_pages#eleven'
  get 'twelve'     => 'static_pages#twelve'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
   resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def statspage
  end

  def about
  end

  def contact
  end
  
  def newgames
  end 
  
  def game
  end
  
  def one
    aberdeen = Scot.find_by(team: 'Aberdeen')
    @wins = aberdeen.wins
    @losses = aberdeen.losses
  end
  
  def two
    celtic = Scot.find_by(team: 'Celtic')
    @wins = celtic.wins
    @losses = celtic.losses
  end
  
  def three
    dundee = Scot.find_by(team: 'Dundee')
    @wins = dundee.wins
    @losses = dundee.losses
  end
  
  def four
    dundee_united = Scot.find_by(team: 'Dundee United')
    @wins = dundee_united.wins
    @losses = dundee_united.losses
  end
  
  def five
    hamilton_academics = Scot.find_by(team: 'Hamilton Academics')
    @wins = hamilton_academics.wins
    @losses = hamilton_academics.losses
  end
  
  def six
    hearts = Scot.find_by(team: 'Hearts')
    @wins = hearts.wins 
    @losses = hearts.losses
  end 
  
  def seven
    inverness_ct = Scot.find_by(team: 'Inverness CT')
    @wins = inverness_ct.wins
    @losses = inverness_ct.losses
  end
  
  def eight
     kilmarnock = Scot.find_by(team: 'Kilmarnock')
    @wins = kilmarnock.wins
    @losses = kilmarnock.losses
  end
  
  def nine
    motherwell = Scot.find_by(team: 'Motherwell')
    @wins = motherwell.wins
    @losses = motherwell.losses
  end
  
  def ten
    partick_thistle = Scot.find_by(team: 'Partick Thistle')
    @wins = partick_thistle.wins
    @losses = partick_thistle.losses
  end
  
  def eleven
    ross_county = Scot.find_by(team: 'Ross County')
    @wins = ross_county.wins
    @losses = ross_county.losses
  end
  
  def twelve
    st_johnstone = Scot.find_by(team: 'St Johnstone')
    @wins = st_johnstone.wins
    @losses = st_johnsone.losses
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/eleven.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>

<h1>Ross County Football Club</h1>
<p>
  
Location of Victoria Park</p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script type"text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 57.595999,
      "lng": -4.418945,
      "picture": {
        "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/static_pages/five.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>

<h1>Hamliton Academical Football Club</h1>
<p>
  
Location of New Douglas Park</p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script type"text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 55.781805,
      "lng": 4.058386,
      "picture": {
        "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});


</script>

<div class="col-3 col-s-12">
  <div class="bside">
  
  <div class
  <div class="bside">
 <div id="data">
  <h1>Hamliton Academical Stats:</h1>
  <p>Wins: <%= @wins %> <br>
  Losses: <%= @losses %> </p>
</div>
  
</div>
</div>
</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<%= stylesheet_link_tag "custom.css.scss" %>
<div class="content">
<div class="row">



<div class="col-6 col-s-9">
  
        
    <% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<%else%>
<div class="bleh" >
<%=image_tag("lo.png", alt: "logo image")%>
<%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%end%>
</div>

<div class="col-3 col-s-12">
  <div class="aside">
  <div class="sideimg">

<%= link_to image_tag("lion.png", alt: "dkj logo") %>,
</div>
</div>
</div>
</div>
</div>

app/views/static_pages/late.html.erb
<% provide(:title, "Latest Reviews") %>
<h1>Latest Reviews</h1>



<p>whats now cool</p>


<li><a href="https://www.igdb.com/reviews">Latest reviews</a></li>

app/views/static_pages/newgames.html.erb
<% provide(:title, "New Games") %>
<h1>New games</h1>


<p>WOooooooo new games :)</p>

http://www.giantbomb.com/new-games

app/views/static_pages/news.html.erb
<% provide(:title, "News") %>
<h1>News</h1>

<p>stuff and things</p>

<li><a href="http://www.giantbomb.com/news/">News</a></li>

app/views/static_pages/nine.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>

<h1>Motherwell Football Club</h1>
<p>
  
Location of Fir Park</p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script type"text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 55.780362,
      "lng": -3.980185,
      "picture": {
        "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/static_pages/one.html.erb
<% provide(:title, "one") %>
<div class="row">
<div class="col-0 col-s-3 menu">

 <ul>
        <li><%= link_to "Home", root_path %></li><br>
        <li><%= link_to "Teams", about_path %></li><br>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Logout", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>

      </ul>

</div>


<div class="col-6 col-s-9">
  
  
<h1>Aberdeen Football Club</h1>
<p>
  
 
Location of Pittodrie Stadium</p>

<div style='width: 600px;'>
  <div id="map" style='width: 600px; height: 400px;'></div>
</div>

<div style='width: 600px;'>
  <div id="map" style='width: 600px; height: 400px;'></div>
</div>
<script type"text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 57.159215,
      "lng": -2.088755,
      "picture": {
        "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

</div>

<div class="col-3 col-s-12">
  <div class="bside">
  <div class="sideimg">
    
    
  <div class
  <div class="bside">
 <div id="data">
  <h1>Aberdeen Stats:</h1>
  <p>Wins: <%= @wins %> <br>
  Losses: <%= @losses %> </p>
</div>
  
</div>
</div>
</div>
</div>
</div>

app/views/static_pages/seven.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>

<h1>Inverness Caledonian Thistle</h1>
<p>
  
Location of Tulloch Caledonian Stadium</p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script type"text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 57.495575,
      "lng": -4.217884,
      "picture": {
        "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/static_pages/six.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>

<h1>Hearts Football Club</h1>
<p>
  
Location of Tynecastle Stadium</p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script type"text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 55.939016,
      "lng": 3.232680,
      "picture": {
        "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/static_pages/three.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>

<h1>Dundee Football Club</h1>
<p>
  
Location of Den Park</p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script type"text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 56.474699,
      "lng": -2.973626,
      "picture": {
        "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/static_pages/twelve.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>

<h1>St Johnstone Football Club</h1>
<p>
  
Location of McDiarmid Park</p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script type"text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 56.409587,
      "lng": -3.476733,
      "picture": {
        "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>